// src/data/personas.js
export const personas = [
  {
    id: 1,
    bgLetra: "C",
    nombre: "Carlos Ruiz",
    posicion: "CEO",
    label: "Potencial alto",
    compania: "Innovar Consulting",
    email: "carlos@innovar.com",
    phone: "+34 913 456 789",
    ubicacion: "Paseo de la Castellana 100, Madrid",
    ultimoContacto: "11 de enero, 2024",
    colorLetra: "text-emerald-700",
    colorBg: "bg-emerald-100",
    detalles: ["ceo", "consulting", "potencial-alto"],
  },
  {
    id: 2,
    bgLetra: "A",
    nombre: "Ana Martin",
    posicion: "CTO",
    label: "Potencial alto",
    compania: "StartUp Digital",
    email: "ana.martin@startup.es",
    phone: "+ 34 915 678 901",
    ubicacion: "Gran Via 28, Madrid",
    ultimoContacto: "11 de enero, 2024",
    colorLetra: "text-emerald-700",
    colorBg: "bg-emerald-100",
    detalles: ["tech", "startup", "innovacion"],
  },
  {
    id: 3,
    bgLetra: "R",
    nombre: "Roberto Silva",
    posicion: "Director Comercial",
    label: "Potencial alto",
    compania: "Global Corp",
    email: "r.silva@gloablcorp.com",
    phone: "+ 34 917 890 123",
    ubicacion: "Torre Picasso, Madrid",
    ultimoContacto: "11 de enero, 2024",
    colorLetra: "text-emerald-700",
    colorBg: "bg-emerald-100",
    detalles: ["corporativo", "ventas", "internacional"],
  }
  
];
